"""Mai2 add PRiSM support

Revision ID: d0f1c7fa9505
Revises: 1d0014d35220
Create Date: 2025-04-02 06:37:10.657372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f1c7fa9505'
down_revision = '1d0014d35220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mai2_playlog', sa.Column('extBool2', sa.Boolean(), nullable=True,server_default=sa.text("NULL")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mai2_playlog', 'extBool2')
    # ### end Alembic commands ###
